name: Deploy Cloud Function

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy my_testgcp_withactions \
              --gen2 \
              --runtime python310 \
              --memory 512MB \
              --trigger-http \
              --entry-point hello_http \
              --region=southamerica-east1 \
              --timeout=540 \
              --cpu 1 \
              --allow-unauthenticated
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}